---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.32.1
  hooks:
  - id: check-github-actions
    additional_dependencies:
    - pip_system_certs==4.0
  - id: check-dependabot
    additional_dependencies:
    - pip_system_certs==4.0
  - id: check-jsonschema
    alias: check-vcpkg-json
    name: Check vcpkg manifest
    files: ^vcpkg\.json$
    args: [--schemafile, 'https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json']
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/pre-commit/mirrors-clang-format
  # This should always match with the version shipped with Visual Studio installed in Azure DevOps images
  rev: v17.0.3
  hooks:
  - id: clang-format
    types_or: [c, c++]
    exclude: .github
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml>=5.1]  # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [-i, --config-files=.cmake_format.py]
    # these are auto-generated from a Python script and should not be formatted
    exclude: .vcpkg-overlays/toolchains/.*_include.cmake
  - id: cmake-lint
    additional_dependencies: [pyyaml>=5.1]  # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [--config-files=.cmake_format.py]
    exclude: .vcpkg-overlays/toolchains/.*_include.cmake
- repo: https://github.com/google/yamlfmt
  rev: v0.16.0
  hooks:
  - id: yamlfmt
    exclude: (.clang-(format|tidy)|tests/python/test_.*)
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
  - id: ruff
  - id: ruff-format
  # manually run `check` and `format` on the preset generator script
  - id: ruff
    alias: ruff-presets
    name: Check .CMakePresets.json.in
    files: .CMakePresets.json.in
    # the hook defines `types_or` which we cannot overrride with a single `types`
    types_or: [file]
  - id: ruff-format
    name: Format .CMakePresets.json.in
    alias: ruff-format-presets
    files: .CMakePresets.json.in
    types_or: [file]
# The markdown-link-check can't access internal or private repos, see
# .markdown_link_check_config.json on how to exclude more than the
# github.com/arup-group
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.13.7
  hooks:
  - id: markdown-link-check
    args: [--quiet, --config=.markdown_link_check_config.json]
    stages: [pre-commit]
- repo: https://github.com/arup-group/oasys-pre-commit-hooks
  rev: 2025.7.0
  hooks:
  - id: codecov-config-validator
    additional_dependencies:
    - pip_system_certs==4.0
  - id: generate-cmake-presets
  - id: validate-cmake-presets
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.7.23
  hooks:
  - id: actionlint
    additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
- repo: local
  hooks:
  - id: no-catch-in-src
    name: Prohibit Catch2 includes in src dir
    language: pygrep
    files: ^src/
    entry: \#include\ [<"]catch2\/
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.2.0
  hooks:
  - id: editorconfig-checker
    alias: ec
# this should go last since it will fix line endings broken by other tools
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: trailing-whitespace
    # The pre-commit check on CI detects some whitespace changes if we include .github
    stages: [pre-commit]
    exclude: .github
  - id: check-added-large-files
    stages: [pre-commit]
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
    stages: [pre-commit]
  - id: end-of-file-fixer
    stages: [pre-commit]
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: check-toml
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --indent=4]
    exclude: .*\.ipynb$
  - id: check-symlinks
  - id: debug-statements
  - id: fix-byte-order-marker
- repo: local
  hooks:
  - id: reject-user-presets
    name: CMakeUserPresets.json must not be committed
    entry: reject CMakeUserPresets.json
    language: fail
    files: CMakeUserPresets.json
