---
# See https://pre-commit.com for more information
exclude: ^\{\{cookiecutter\.project_slug\}\}

# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  # this is the version used across most products due to VS 2022 shipping with it
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c, c++]
    exclude: .github
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml>=5.1]     # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [-i, --config-files=.cmake_format.py]
    exclude: config.h.cmake
  - id: cmake-lint
    additional_dependencies: [pyyaml>=5.1]     # see https://github.com/cheshirekow/cmake-format-precommit/pull/4#issuecomment-943444582
    args: [--config-files=.cmake_format.py]
    exclude: config.h.cmake
- repo: https://github.com/arup-group/oasys-yamlfmt
  rev: 0.3.1
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '119']
    exclude: .clang-(format|tidy)
- repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
  rev: v0.9.6
  hooks:
  - id: ruff
    args: [--config=.ruff.toml]
  - id: ruff-format
    args: [--config=.ruff.toml]
# The markdown-link-check can't access internal or private repos, see
# .markdown_link_check_config.json on how to exclude more than the
# github.com/arup-group
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.12.2
  hooks:
  - id: markdown-link-check
    args: [--quiet, --config=.markdown_link_check_config.json]
- repo: https://github.com/arup-group/oasys-pre-commit-hooks
  rev: 2025.3.0
  hooks:
  - id: codecov-config-validator
    additional_dependencies:
    - pip_system_certs==4.0
  - id: generate-cmake-presets
  - id: validate-cmake-presets
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.7.23
  hooks:
  - id: actionlint
    additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.2.0
  hooks:
  - id: editorconfig-checker
    alias: ec
# this should go last since it will fix line endings broken by other tools
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    # The pre-commit check on CI detects some whitespace changes if we include .github
    exclude: .github
  - id: check-added-large-files
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: check-toml
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --indent=4]
    exclude: .*\.ipynb$
  - id: check-symlinks
  - id: debug-statements
  - id: fix-byte-order-marker
