---
# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
    - v*

jobs:
  pypi:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      name: Setup UV + Python
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/pyproject.toml
          **/uv.lock
    - name: Build dist artefacts
      run: |
        uv sync
        uv run python -m build --sdist --wheel --outdir dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        user: __token__
        password: ${{"{{ secrets.PYPI_TOKEN }}"}}
  github:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{"{{ secrets.GITHUB_TOKEN }}"}}
      with:
        tag_name: ${{"{{ github.ref }}"}}
        release_name: ${{"{{ github.ref }}"}}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false
