---
on:
  push:
    branches:
    - main
  merge_group:
  pull_request:
    branches:
    - main

concurrency:
  group: {% raw %}${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}{% endraw %}
  cancel-in-progress: true

name: pytest
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["{{ cookiecutter.minimum_python_version }}", "> {{ cookiecutter.minimum_python_version }}"]
        os: ["ubuntu-24.04", "windows-2025"]

    steps:
    - uses: actions/checkout@v4
    
    - uses: astral-sh/setup-uv@v5
      name: Setup UV + Python
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/pyproject.toml
          **/uv.lock
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Lint with ruff
      run: |
        uv run --frozen ruff check .
        
    - name: Type check with mypy
      run: |
        uv run --frozen mypy src/{{ cookiecutter.__module_name }}/
        
    - name: Test with pytest
      run: |
        uv run --frozen pytest

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        env_vars: OS,PYTHON_VERSION
        fail_ci_if_error: true
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
