---
on:
  push:
    branches:
    - main
  merge_group:
  pull_request:
    branches:
    - main

name: pytest
jobs:
  py-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-2022, py: '3.7'}
        - {os: ubuntu-22.04, py: '3.9'}
        - {os: ubuntu-22.04, py: '3.12'}

    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      OS: ${{ matrix.config.os }}
      PYTHON: ${{ matrix.config.py }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[ci]
    - name: run pytest
      run: |
        pytest
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: build docs
      run: |
        python -m pip install .[docs]
        make -C docs html
