# This file is generated by .CMakePresets.json.in

set(VCPKG_CXX_FLAGS "")
set(VCPKG_CXX_FLAGS_DEBUG "-Og -g -DOASYS_CORE_ENABLE_CHECKS")
set(VCPKG_CXX_FLAGS_RELEASE "-O3 ")
set(VCPKG_CXX_FLAGS_RELWITHCHECKS "-O3 -g -DOASYS_CORE_ENABLE_CHECKS")
set(VCPKG_CXX_FLAGS_COVERAGE "-Og -g -fcoverage-mcdc -fprofile-instr-generate -fcoverage-mapping -DOASYS_CORE_ENABLE_CHECKS")
